[package]
name = "Enarx-Demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rml = "0.1.0"
csv = "1.1"
polars = "0.14.2"
polars-core = {version = "0.14.2", features=["ndarray"]}
arrow = "4.3.0"
